### ISSUE TITLE
Where is meta_prompt_agent_dialogue.txt?

### ISSUE THREAD

**Issue by lijiazheng99** [choosewhatulike/trainable-agents#13]
Thank the authors for the great work! 

I am currently attempting to replicate the single and multi-turn interview evaluations and have encountered a couple of issues that I hope you could help clarify:

- Code Discrepancy: In [eval_utils.py, line 357](https://github.com/choosewhatulike/trainable-agents/blob/4f7a9367f7b449596a49624a95d12b8f75b9ff3a/eval_utils.py#L357), the code snippet seems to mistakenly include an extra "gpt-3.5-turbo". Should it be updated to response = decoder_for_openai(self.model_name, prompt, max_length, temperature, apikey=API_KEY)?
- Missing File: I am unable to find the meta_prompt_agent_dialogue.txt file as [mentioned here](https://github.com/choosewhatulike/trainable-agents/blob/4f7a9367f7b449596a49624a95d12b8f75b9ff3a/eval_utils.py#L89). The file prompt_agent_dialogue.txt available in the repository does not seem to match the expected content. Could you please provide guidance on where I might locate the meta_prompt_agent_dialogue.txt file?

Thank you very much!

**Comment by choosewhatulike** [comment]
Hi, thanks for raising this issue!

- For the [eval_utils.py, line 357](https://github.com/choosewhatulike/trainable-agents/blob/4f7a9367f7b449596a49624a95d12b8f75b9ff3a/eval_utils.py#L357),  it should be `decoder_for_local_chat`. It is implemented to evaluate open-source models as baselines. You can use `LocalCharacter` for SFT models.
-  meta_prompt_agent_dialogue.txt  should be replaced by agent_meta_prompt_sft.txt file, which is under `data/seed_data/prompts/`

I apologize for these typos and will update the files to fix them. Since the evaluation code is initially separated from our training data construction code, it may have some unchanged typos.  

If you have any new questions, feel free to ask!

**Comment by lijiazheng99** [comment]
Thank you for clarifying!
